---

- hosts: SELS_jenkins_slave
  become: true
  become_method: sudo
  tasks:
    - name: Adding repo
      zypper_repository:
        repo: 'https://download.opensuse.org/repositories/devel:/languages:/nodejs/SLE_12/devel:languages:nodejs.repo'
        state: present

    - name: Installing the Nodejs and NPM 
      zypper:
        name: 
          - nodejs
          - npm
        state: latest

